// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __FLEX_CALLBACKS__
#define __FLEX_CALLBACKS__


#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include "command-interpreter/command-interpreter2.h"
#include "heartbeat/heartbeat.h"
#include "hal/hal.h"
#include "serial/serial.h"
#include EMBER_AF_API_EMBER_TYPES
#include EMBER_AF_API_HAL
#include EMBER_AF_API_SIM_EEPROM


/** @brief Main Application Entry Point
 *
 * This is the main application entry point. All applications
 * must implement this function.
 */
int main(MAIN_FUNCTION_PARAMETERS);

// Handler called whenever the radio is powered on.
void halRadioPowerUpHandler(void);

// Handler called whenever the radio is powered off.
void halRadioPowerDownHandler(void);

/** @brief COM Power Down
 *
 * A callback invoked by the Serial plugin before powering down.
 *
 */
void emberAfPluginSerialComPowerDownCallback(void);

/** @brief COM Power Up
 *
 * A callback invoked by the Serial plugin after powering up.
 *
 */
void emberAfPluginSerialComPowerUpCallback(void);

/** @brief Main Init
 *
 * This function is called when the application starts and can be used to
 * perform any additional initialization required at system startup.
 */
void emberAfMainInitCallback(void);

/** @brief Main Tick
 *
 * This function is called in each iteration of the main application loop and
 * can be used to perform periodic functions.  The frequency with which this
 * function is called depends on how quickly the main loop runs.  If the
 * application blocks at any time during the main loop, this function will not
 * be called until execution resumes. Sleeping and idling will block.
 */
void emberAfMainTickCallback(void);

/** @brief Stack Status
 *
 * This function is called when the stack status changes.  This callbacks
 * provides applications an opportunity to be notified of changes to the stack
 * status and take appropriate action.
 *
 * @param status   Ver.: always
 */
void emberAfStackStatusCallback(EmberStatus status);

/** @brief Incoming Message
 *
 * This function is called when a message is received.
 *
 * @param message   Ver.: always
 */
void emberAfIncomingMessageCallback(EmberIncomingMessage *message);

/** @brief Incoming Mac Message
 *
 * This function is called when a node of ::EMBER_MAC_MODE_DEVICE type or
 * ::EMBER_MAC_MODE_SLEEPY_DEVICE has has received a MAC frame.
 *
 * @param message   Ver.: always
 */
void emberAfIncomingMacMessageCallback(EmberIncomingMacMessage *message);

/** @brief Message Sent
 *
 * This function is called to indicate whether an outgoing message was
 * successfully transmitted or to indicate the reason of failure.
 *
 * @param status    Ver.: always
 * @param message   Ver.: always
 */
void emberAfMessageSentCallback(EmberStatus status,
                                EmberOutgoingMessage *message);

/** @brief Mac Message Sent
 *
 * This function is called at a node of ::EMBER_MAC_MODE_DEVICE type or
 * ::EMBER_MAC_MODE_SLEEPY_DEVICE type to indicate whether an outgoing MAC frame
 * was successfully transmitted or to indicate the reason of failure.
 *
 * @param status    Ver.: always
 * @param message   Ver.: always
 */
void emberAfMacMessageSentCallback(EmberStatus status,
                                   EmberOutgoingMacMessage *message);

/** @brief Child Join
 *
 * This function is called when a node has joined the network.
 *
 * @param nodeType   Ver.: always
 * @param nodeId     Ver.: always
 */
void emberAfChildJoinCallback(EmberNodeType nodeType,
                              EmberNodeId nodeId);

/** @brief Active Scan Complete
 *
 * This function is called when a node has completed an active scan.
 */
void emberAfActiveScanCompleteCallback(void);

/** @brief Child Join
 *
 * This function is called when a node has joined the network.
 *
 * @param mean       Ver.: always
 * @param min        Ver.: always
 * @param max        Ver.: always
 * @param variance   Ver.: always
 */
void emberAfEnergyScanCompleteCallback(int8_t mean,
                                       int8_t min,
                                       int8_t max,
                                       uint16_t variance);

/** @brief Mark Application Buffers
 *
 * This function is called when the application must mark its buffers.  Buffers
 * that are not marked will be reclaimed by the stack.
 */
void emberAfMarkApplicationBuffersCallback(void);

/** @brief Incoming Beacon
 *
 * This function is called when a node is performing an active scan and a beacon
 * is received.
 *
 * @deprecated This callback is deprecated and will be removed in a future
 *  release. The application should implement
 *  ::emberAfIncomingBeaconExtendedCallback instead.
 *
 * @param panId          Ver.: always
 * @param nodeId         Ver.: always
 * @param rssi           Ver.: always
 * @param permitJoining  Ver.: always
 * @param payloadLength  Ver.: always
 * @param payload        Ver.: always
 */
void emberAfIncomingBeaconCallback(EmberPanId panId,
                                   EmberNodeId nodeId,
                                   int8_t rssi,
                                   bool permitJoining,
                                   uint8_t payloadLength,
                                   uint8_t *payload);

/** @brief Incoming Beacon Extended
 *
 * This function is called when a node is performing an active scan and a beacon
 * is received.
 *
 * @param panId                Ver.: always
 * @param source               Ver.: always
 * @param rssi                 Ver.: always
 * @param permitJoining        Ver.: always
 * @param beaconFieldsLength   Ver.: always
 * @param beaconFields         Ver.: always
 * @param beaconPayloadLength  Ver.: always
 * @param beaconPayload        Ver.: always
 */
void emberAfIncomingBeaconExtendedCallback(EmberPanId panId,
                                           EmberMacAddress *source,
                                           int8_t rssi,
                                           bool permitJoining,
                                           uint8_t beaconFieldsLength,
                                           uint8_t *beaconFields,
                                           uint8_t beaconPayloadLength,
                                           uint8_t *beaconPayload);

/** @brief Frequency Hopping Start Client Complete
 *
 * This function is called when a frequency hopping client completed the start
 * procedure.
 *
 * @param status        Ver.: always
 */
void emberAfFrequencyHoppingStartClientCompleteCallback(EmberStatus status);

/** @brief Radio Needs Calibrating
 *
 * This function is called when the radio hardware has determined that radio
 * calibration is needed.
 */
void emberAfRadioNeedsCalibratingCallback(void);

/** @brief Stack Idle
 *
 * This function is called when the stack is about to idle the CPU.
 *
 * @param idleTimeMs    Ver.: always
 *
 * @return true if the application will handle idling the CPU, false otherwise.
 */
bool emberAfStackIdleCallback(uint32_t *idleTimeMs);

/** @brief The Simulated EEPROM callback function, implemented by the
 * application.
 *
 * @param status  An ::EmberStatus error code indicating one of the conditions
 * described below.
 *
 * This callback will report an EmberStatus of
 * ::EMBER_SIM_EEPROM_ERASE_PAGE_GREEN whenever a token is set and a page needs
 * to be erased. If the main application loop does not periodically
 * call halSimEepromErasePage(), it is best to then erase a page in
 * response to ::EMBER_SIM_EEPROM_ERASE_PAGE_GREEN.
 *
 * This callback will report an EmberStatus of ::EMBER_SIM_EEPROM_ERASE_PAGE_RED
 * when the pages <i>must</i> be erased to prevent data loss.
 * halSimEepromErasePage() needs to be called until it returns 0 to indicate
 * there are no more pages that need to be erased.  Ignoring
 * this indication and not erasing the pages will cause dropping the new data
 * trying to be written.
 *
 * This callback will report an EmberStatus of ::EMBER_SIM_EEPROM_FULL when
 * the new data cannot be written due to unerased pages.  <b>Not erasing
 * pages regularly, not erasing in response to
 * ::EMBER_SIM_EEPROM_ERASE_PAGE_GREEN, or not erasing in response to
 * ::EMBER_SIM_EEPROM_ERASE_PAGE_RED will cause
 * ::EMBER_SIM_EEPROM_FULL and the new data will be lost!.</b>  Any future
 * write attempts will be lost as well.
 *
 * This callback will report an EmberStatus of ::EMBER_SIM_EEPROM_REPAIRING
 * when the Simulated EEPROM needs to repair itself. While there's nothing
 * for an app to do when the SimEE is going to repair itself (SimEE has to
 * be fully functional for the rest of the system to work), alert the
 * application to the fact that repairing is occurring. There are debugging
 * scenarios where an app might want to know that repairing is happening;
 * such as monitoring frequency.
 * @note  Common situations will trigger an expected repair, such as using
 *        a new chip or changing token definitions.
 *
 * If the callback ever reports the status ::EMBER_ERR_FLASH_WRITE_INHIBITED or
 * ::EMBER_ERR_FLASH_VERIFY_FAILED, a catastrophic failure has occurred in
 * flash writing, meaning either the address being written is not empty or the
 * write itself has failed. If ::EMBER_ERR_FLASH_WRITE_INHIBITED is
 * encountered, the function ::halInternalSimEeRepair(false) should be called
 * and the chip should then be reset to allow proper initialization to recover.
 * If ::EMBER_ERR_FLASH_VERIFY_FAILED is encountered the Simulated EEPROM (and
 * tokens) on the specific chip with this error should not be trusted anymore.
 *
 */
void halSimEepromCallback(EmberStatus status);

void emberIncomingMessageHandler(EmberIncomingMessage *message);

void emberIncomingMacMessageHandler(EmberIncomingMacMessage *message);

void emberMessageSentHandler(EmberStatus status, EmberOutgoingMessage *message);

void emberMacMessageSentHandler(EmberStatus status, 
                                EmberOutgoingMacMessage *message);

void emberStackStatusHandler(EmberStatus status);

void emberStackIsrHandler(void);

//bool emberStackIdleHandler(uint32_t *idleTimeMs);

void emberMarkApplicationBuffersHandler(void);

void emberRadioNeedsCalibratingHandler(void);

void emberChildJoinHandler(EmberNodeType nodeType,
                           EmberNodeId nodeId);

void emberIncomingBeaconHandler(EmberPanId panId,
                                EmberNodeId nodeId,
                                int8_t rssi,
                                bool permitJoining,
                                uint8_t payloadLength,
                                uint8_t *payload);

void emberIncomingBeaconExtendedHandler(EmberPanId panId,
                                        EmberMacAddress *source,
                                        int8_t rssi,
                                        bool permitJoining,
                                        uint8_t beaconFieldsLength,
                                        uint8_t *beaconFields,
                                        uint8_t beaconPayloadLength,
                                        uint8_t *beaconPayload);

void emberActiveScanCompleteHandler(void);

void emberEnergyScanCompleteHandler(int8_t mean,
                                    int8_t min,
                                    int8_t max,
                                    uint16_t variance);

#endif // __FLEX_CALLBACKS__
