// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void reportHandler(void);
extern EmberEventControl reportControl;

//void emberAfPluginPollEventHandler(void);
//extern EmberEventControl emberAfPluginPollEventControl;



const EmberEventData emAppEvents[] = {
  {&reportControl, reportHandler},
//{&emberAfPluginPollEventControl, emberAfPluginPollEventHandler},
  {NULL, NULL}
};
