// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __FLEX_BOOKKEEPING_H__
#define __FLEX_BOOKKEEPING_H__


void emberAfInit(void);

void emberAfTick(void);

void emberAfStackStatus(EmberStatus status);

void emberAfStackIsr(void);

void emberAfIncomingMessage(EmberIncomingMessage* message);

void emberAfIncomingMacMessage(EmberIncomingMacMessage* message);

void emberAfMessageSent(EmberStatus status, EmberOutgoingMessage* message);

void emberAfMacMessageSent(EmberStatus status, EmberOutgoingMacMessage* message);

void emberAfChildJoin(EmberNodeType nodeType, EmberNodeId nodeId);

void emberAfIncomingBeacon(EmberPanId panId, EmberNodeId nodeId, int8_t rssi, bool permitJoining, uint8_t payloadLength, uint8_t* payload);

void emberAfIncomingBeaconExtended(EmberPanId panId, EmberMacAddress *source, int8_t rssi, bool permitJoining, uint8_t beaconFieldsLength, uint8_t *beaconFields, uint8_t beaconPayloadLength, uint8_t *beaconPayload);

void emberAfActiveScanComplete(void);

void emberAfEnergyScanComplete(int8_t mean, int8_t min, int8_t max, uint16_t variance);

void emberMarkApplicationBuffersHandler(void);

void emberAfFrequencyHoppingStartClientComplete(EmberStatus status);

void emberAfRadioNeedsCalibrating(void);

#endif // __FLEX_BOOKKEEPING_H__
