#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ACMP1]
// [ACMP1]$

// $[ADC0]
// [ADC0]$

// $[ANTDIV]
// [ANTDIV]$

// $[BATTERYMON]
// [BATTERYMON]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BULBPWM]
// [BULBPWM]$

// $[BULBPWM_COLOR]
// [BULBPWM_COLOR]$

// $[BUTTON]
// [BUTTON]$

// [CMU]
#define HAL_CLK_HFCLK_SOURCE                  (HAL_CLK_HFCLK_SOURCE_HFXO)
#define HAL_CLK_LFECLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFBCLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_LFXO_PRESENT                  (1)
#define BSP_CLK_HFXO_PRESENT                  (1)
#define BSP_CLK_LFXO_INIT                      CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                    (0U)
#define BSP_CLK_LFXO_FREQ                     (32768U)
#define HAL_CLK_LFACLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_HFXO_FREQ                     (38400000UL)
#define BSP_CLK_HFXO_INIT                      CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_CTUNE_TOKEN              (1)
#define HAL_CLK_HFXO_AUTOSTART                (HAL_CLK_HFXO_AUTOSTART_NONE)
// [CMU]

// $[COEX]
// [COEX]$

// $[CS5463]
// [CS5463]$

// $[CSEN]
// [CSEN]$

// $[DCDC]
#define BSP_DCDC_PRESENT                      (1)

#define HAL_DCDC_BYPASS                       (0)
#define BSP_DCDC_INIT                          EMU_DCDCINIT_DEFAULT
// [DCDC]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[EZRADIOPRO]
// [EZRADIOPRO]$

// $[FEM]
// [FEM]$

// $[GPIO]
// [GPIO]$

// $[I2C0]
#define PORTIO_I2C0_SCL_PIN                   (11U)
#define PORTIO_I2C0_SCL_PORT                  (gpioPortC)
#define PORTIO_I2C0_SCL_LOC                   (15U)

#define PORTIO_I2C0_SDA_PIN                   (10U)
#define PORTIO_I2C0_SDA_PORT                  (gpioPortC)
#define PORTIO_I2C0_SDA_LOC                   (15U)

#define HAL_I2C0_ENABLE                       (1)

#define HAL_I2C0_LOW_HIGH_RATIO               (_I2C_CTRL_CLHR_STANDARD)
#define HAL_I2C0_INIT_ENABLE                  (0)
#define HAL_I2C0_MAX_BUS_FREQ                 (0UL)
#define HAL_I2C0_MASTER                       (0)
// [I2C0]$

// $[I2C1]
// [I2C1]$

// $[I2CSENSOR]
#define HAL_I2CSENSOR_ENABLE                  (1)

#define BSP_I2CSENSOR_ENABLE_PIN              (9U)
#define BSP_I2CSENSOR_ENABLE_PORT             (gpioPortF)

#define BSP_I2CSENSOR_PERIPHERAL              (HAL_I2C_PORT_I2C0)
#define HAL_I2CSENSOR_LOW_HIGH_RATIO          (_I2C_CTRL_CLHR_STANDARD)
#define HAL_I2CSENSOR_INIT_ENABLE             (0)
#define HAL_I2CSENSOR_MASTER                  (0)
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
#define BSP_LED_PRESENT                       (1)

#define BSP_LED0_PIN                          (5U)
#define BSP_LED0_PORT                         (gpioPortA)

#define BSP_LED1_PIN                          (6U)
#define BSP_LED1_PORT                         (gpioPortA)

#define HAL_LED_ENABLE                        { 0, 1 }
#define HAL_LED_COUNT                         (0U)
#define BSP_LED_COUNT                         (2U)
#define BSP_LED_INIT                          { { BSP_LED0_PORT, BSP_LED0_PIN }, { BSP_LED1_PORT, BSP_LED1_PIN } }
// [LED]$

// $[LESENSE]
// [LESENSE]$

// $[LETIMER0]
// [LETIMER0]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[PA]
#define HAL_PA_ENABLE                         (1)

#define HAL_PA_RAMP                           (10UL)
#define HAL_PA_2P4_LOWPOWER                   (0)
#define HAL_PA_POWER                          (252U)
#define BSP_PA_VOLTAGE                        (3300U)
#define HAL_PA_CURVE_HEADER                    "pa_curves_efr32.h"
// [PA]$

// $[PCNT0]
// [PCNT0]$

// $[PCNT1]
// [PCNT1]$

// $[PCNT2]
// [PCNT2]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[PTI]
#define PORTIO_PTI_DFRAME_PIN                 (13U)
#define PORTIO_PTI_DFRAME_PORT                (gpioPortB)
#define PORTIO_PTI_DFRAME_LOC                 (6U)

#define PORTIO_PTI_DOUT_PIN                   (12U)
#define PORTIO_PTI_DOUT_PORT                  (gpioPortB)
#define PORTIO_PTI_DOUT_LOC                   (6U)

#define HAL_PTI_ENABLE                        (1)

#define BSP_PTI_DFRAME_PIN                    (13U)
#define BSP_PTI_DFRAME_PORT                   (gpioPortB)
#define BSP_PTI_DFRAME_LOC                    (6U)

#define BSP_PTI_DOUT_PIN                      (12U)
#define BSP_PTI_DOUT_PORT                     (gpioPortB)
#define BSP_PTI_DOUT_LOC                      (6U)

#define HAL_PTI_MODE                          (HAL_PTI_MODE_UART)
#define HAL_PTI_BAUD_RATE                     (1600000UL)
// [PTI]$

// $[PYD1698]
// [PYD1698]$

// $[SERIAL]
#define HAL_SERIAL_USART0_ENABLE              (1)
#define BSP_SERIAL_APP_PORT                   (HAL_SERIAL_PORT_USART0)
#define HAL_SERIAL_LEUART0_ENABLE             (0)
#define HAL_SERIAL_USART1_ENABLE              (1)
#define HAL_SERIAL_USART2_ENABLE              (0)
#define HAL_SERIAL_USART3_ENABLE              (0)
#define HAL_SERIAL_RXWAKE_ENABLE              (0)
#define HAL_SERIAL_IDLE_WAKE_ENABLE           (1)
#define BSP_SERIAL_APP_CTS_PIN                (2U)
#define BSP_SERIAL_APP_CTS_PORT               (gpioPortA)
#define BSP_SERIAL_APP_CTS_LOC                (30U)

#define BSP_SERIAL_APP_RX_PIN                 (1U)
#define BSP_SERIAL_APP_RX_PORT                (gpioPortA)
#define BSP_SERIAL_APP_RX_LOC                 (0U)

#define BSP_SERIAL_APP_TX_PIN                 (0U)
#define BSP_SERIAL_APP_TX_PORT                (gpioPortA)
#define BSP_SERIAL_APP_TX_LOC                 (0U)

#define BSP_SERIAL_APP_RTS_PIN                (3U)
#define BSP_SERIAL_APP_RTS_PORT               (gpioPortA)
#define BSP_SERIAL_APP_RTS_LOC                (30U)

#define HAL_SERIAL_APP_RX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_APP_BAUD_RATE              (115200UL)
#define HAL_SERIAL_APP_RXSTOP                 (16UL)
#define HAL_SERIAL_APP_RXSTART                (16UL)
#define HAL_SERIAL_APP_TX_QUEUE_SIZE          (128UL)
#define HAL_SERIAL_APP_FLOW_CONTROL           (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]
// [TIMER1]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
#define PORTIO_USART0_CTS_PIN                 (2U)
#define PORTIO_USART0_CTS_PORT                (gpioPortA)
#define PORTIO_USART0_CTS_LOC                 (30U)

#define PORTIO_USART0_RTS_PIN                 (3U)
#define PORTIO_USART0_RTS_PORT                (gpioPortA)
#define PORTIO_USART0_RTS_LOC                 (30U)

#define PORTIO_USART0_RX_PIN                  (1U)
#define PORTIO_USART0_RX_PORT                 (gpioPortA)
#define PORTIO_USART0_RX_LOC                  (0U)

#define PORTIO_USART0_TX_PIN                  (0U)
#define PORTIO_USART0_TX_PORT                 (gpioPortA)
#define PORTIO_USART0_TX_LOC                  (0U)

#define HAL_USART0_ENABLE                     (1)

#define BSP_USART0_CTS_PIN                    (2U)
#define BSP_USART0_CTS_PORT                   (gpioPortA)
#define BSP_USART0_CTS_LOC                    (30U)

#define BSP_USART0_RX_PIN                     (1U)
#define BSP_USART0_RX_PORT                    (gpioPortA)
#define BSP_USART0_RX_LOC                     (0U)

#define BSP_USART0_TX_PIN                     (0U)
#define BSP_USART0_TX_PORT                    (gpioPortA)
#define BSP_USART0_TX_LOC                     (0U)

#define BSP_USART0_RTS_PIN                    (3U)
#define BSP_USART0_RTS_PORT                   (gpioPortA)
#define BSP_USART0_RTS_LOC                    (30U)

#define HAL_USART0_RX_QUEUE_SIZE              (128UL)
#define HAL_USART0_BAUD_RATE                  (115200UL)
#define HAL_USART0_RXSTOP                     (16UL)
#define HAL_USART0_RXSTART                    (16UL)
#define HAL_USART0_TX_QUEUE_SIZE              (128UL)
#define HAL_USART0_FLOW_CONTROL               (HAL_USART_FLOW_CONTROL_NONE)
// [USART0]$

// $[USART1]
#define PORTIO_USART1_RX_PIN                  (5U)
#define PORTIO_USART1_RX_PORT                 (gpioPortF)
#define PORTIO_USART1_RX_LOC                  (28U)

#define PORTIO_USART1_TX_PIN                  (6U)
#define PORTIO_USART1_TX_PORT                 (gpioPortF)
#define PORTIO_USART1_TX_LOC                  (30U)

#define HAL_USART1_ENABLE                     (1)

#define BSP_USART1_RX_PIN                     (5U)
#define BSP_USART1_RX_PORT                    (gpioPortF)
#define BSP_USART1_RX_LOC                     (28U)

#define BSP_USART1_TX_PIN                     (6U)
#define BSP_USART1_TX_PORT                    (gpioPortF)
#define BSP_USART1_TX_LOC                     (30U)

#define HAL_USART1_RX_QUEUE_SIZE              (128UL)
#define HAL_USART1_BAUD_RATE                  (9600UL)
#define HAL_USART1_RXSTOP                     (16UL)
#define HAL_USART1_RXSTART                    (16UL)
#define HAL_USART1_TX_QUEUE_SIZE              (128UL)
#define HAL_USART1_FLOW_CONTROL               (HAL_USART_FLOW_CONTROL_NONE)
// [USART1]$

// $[USART2]
#define PORTIO_USART2_CLK_PIN                 (7U)
#define PORTIO_USART2_CLK_PORT                (gpioPortF)
#define PORTIO_USART2_CLK_LOC                 (18U)

#define PORTIO_USART2_CS_PIN                  (1U)
#define PORTIO_USART2_CS_PORT                 (gpioPortK)
#define PORTIO_USART2_CS_LOC                  (27U)

#define PORTIO_USART2_RX_PIN                  (2U)
#define PORTIO_USART2_RX_PORT                 (gpioPortK)
#define PORTIO_USART2_RX_LOC                  (30U)

#define PORTIO_USART2_TX_PIN                  (0U)
#define PORTIO_USART2_TX_PORT                 (gpioPortK)
#define PORTIO_USART2_TX_LOC                  (29U)

#define HAL_USART2_ENABLE                     (1)

#define BSP_USART2_CS_PIN                     (1U)
#define BSP_USART2_CS_PORT                    (gpioPortK)
#define BSP_USART2_CS_LOC                     (27U)

#define BSP_USART2_CLK_PIN                    (7U)
#define BSP_USART2_CLK_PORT                   (gpioPortF)
#define BSP_USART2_CLK_LOC                    (18U)

#define BSP_USART2_MISO_PIN                   (2U)
#define BSP_USART2_MISO_PORT                  (gpioPortK)
#define BSP_USART2_MISO_LOC                   (30U)

#define BSP_USART2_MOSI_PIN                   (0U)
#define BSP_USART2_MOSI_PORT                  (gpioPortK)
#define BSP_USART2_MOSI_LOC                   (29U)

#define HAL_USART2_FREQUENCY                  (1000000UL)
// [USART2]$

// $[USART3]
// [USART3]$

// $[VCOM]
#define HAL_VCOM_ENABLE                       (1)

#define BSP_VCOM_ENABLE_PIN                   (4U)
#define BSP_VCOM_ENABLE_PORT                  (gpioPortA)

// [VCOM]$

// $[VDAC0]
// [VDAC0]$

// $[VUART]
// [VUART]$

// $[WDOG]
// [WDOG]$

// $[WTIMER0]
// [WTIMER0]$

// $[WTIMER1]
// [WTIMER1]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                  (HAL_CLK_HFCLK_SOURCE_HFXO)
#define HAL_CLK_LFECLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define HAL_CLK_LFBCLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_LFXO_PRESENT                  (1)
#define BSP_CLK_HFXO_PRESENT                  (1)
#define BSP_CLK_LFXO_INIT                      CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_CTUNE                    (0U)
#define BSP_CLK_LFXO_FREQ                     (32768U)
#define HAL_CLK_LFACLK_SOURCE                 (HAL_CLK_LFCLK_SOURCE_LFRCO)
#define BSP_CLK_HFXO_FREQ                     (38400000UL)
#define BSP_CLK_HFXO_CTUNE                    (-1)
#define BSP_CLK_HFXO_INIT                      CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_CTUNE_TOKEN              (1)
#define HAL_CLK_HFXO_AUTOSTART                (HAL_CLK_HFXO_AUTOSTART_NONE)
// [CMU]$

