// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2
#include "protocolored.h"
void emberPrintCommandTable(void);
void display_command(void);
void infoCommand(void);
void windowCommand(void);
void autoposCommand(void);
void forceDiscoveryCommand(void);
void standbyCommand(void);
void GNSSManualCommand(void);

#if (RED_USADA!=RED_DEMO2)
void setFrequencyCommand(void);
void activeScanCommand(void);
void energyScanCommand(void);
void joinNetworkCommand(void);
void joinCommissionedCommand(void);
void emberResetNetworkState(void);
void setPermitJoinCommand(void);
void pollCommand(void);
void purgeIndirectCommand(void);
void halReboot(void);
void sendCommand(void);
void envio_simple(void);
void setAllocateAddressFlagCommand(void);
void setBeaconPayloadCommand(void);
void setSecurityKeyCommand(void);
void setOptionsCommand(void);
void setPollDestinationCommand(void);
#endif
EmberCommandEntry emberCommandTable[] = {
#if (RED_USADA!=RED_DEMO2)
  emberCommandEntryAction("set-frequency", setFrequencyCommand, "v", ""),
  emberCommandEntryAction("active-scan", activeScanCommand, "u", ""),
  emberCommandEntryAction("energy-scan", energyScanCommand, "uu", ""),
  emberCommandEntryAction("envia", envio_simple, "vb", ""),
#endif
  emberCommandEntryAction("display", display_command, "uuuuu", ""),
  emberCommandEntryAction("help", emberPrintCommandTable, "", ""),
  emberCommandEntryAction("info", infoCommand, "", ""),
  emberCommandEntryAction("window", windowCommand, "v", ""),		//tercer argumento es el tipo y numero de entradas (v uint16)
  emberCommandEntryAction("autopos", autoposCommand, "", ""),
  emberCommandEntryAction("force-discovery", forceDiscoveryCommand, "", ""),
  emberCommandEntryAction("standby", standbyCommand, "u", ""),
  emberCommandEntryAction("GNSS", GNSSManualCommand, "uuvvu", ""),
#if (RED_USADA!=RED_DEMO2)
  emberCommandEntryAction("join", joinNetworkCommand, "uvsu", ""),
  emberCommandEntryAction("join-commissioned", joinCommissionedCommand, "uvvsu", ""),
  emberCommandEntryAction("leave", emberResetNetworkState, "", ""),
  emberCommandEntryAction("pjoin", setPermitJoinCommand, "u", ""),
  emberCommandEntryAction("poll", pollCommand, "", ""),
  emberCommandEntryAction("purge-indirect", purgeIndirectCommand, "", ""),
  emberCommandEntryAction("reset", halReboot, "", ""),
  emberCommandEntryAction("send", sendCommand, "vvbvbvvb", ""),
  emberCommandEntryAction("set-allocate-addr", setAllocateAddressFlagCommand, "u", ""),
  emberCommandEntryAction("set-beacon-payload", setBeaconPayloadCommand, "b", ""),
  emberCommandEntryAction("set-key", setSecurityKeyCommand, "b", ""),
  emberCommandEntryAction("set-options", setOptionsCommand, "u", ""),
  emberCommandEntryAction("set-poll-dest", setPollDestinationCommand, "vb", ""),
#endif
#ifdef EMBER_AF_ENABLE_CUSTOM_COMMANDS
  CUSTOM_COMMANDS
#endif // EMBER_AF_ENABLE_CUSTOM_COMMANDS
  emberCommandEntryTerminator(),
};
