// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __EMBER_AF_DEBUG_PRINTING_CONFIGURATION__
#define __EMBER_AF_DEBUG_PRINTING_CONFIGURATION__




// This file contains the generated macros for the debug printing
// Global macro, if this is commented out, there is no printing
#define EMBER_AF_PRINT_ENABLE



// Generated bit array and name array that is used by thedebug printing library.
#define EMBER_AF_PRINT_CORE 0x0001
#define EMBER_AF_PRINT_APP 0x0002
#define EMBER_AF_PRINT_BITS { 0x03 }
#define EMBER_AF_PRINT_NAMES { \
  "Core",\
  "Application",\
  NULL\
}
#define EMBER_AF_PRINT_NAME_NUMBER 2


// Generated functions for use within plugin Security XXTEA Stub
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB)
#define emberAfPluginStackXxteaSecurityStubPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB, __VA_ARGS__)
#define emberAfPluginStackXxteaSecurityStubPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackXxteaSecurityStubFlush()
#define emberAfPluginStackXxteaSecurityStubDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB) ) { x; }
#define emberAfPluginStackXxteaSecurityStubPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB, (buffer), (len), (withSpace))
#define emberAfPluginStackXxteaSecurityStubPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB, (buffer))
#else
#define emberAfPluginStackXxteaSecurityStubPrint(...)
#define emberAfPluginStackXxteaSecurityStubPrintln(...)
#define emberAfPluginStackXxteaSecurityStubFlush()
#define emberAfPluginStackXxteaSecurityStubDebugExec(x)
#define emberAfPluginStackXxteaSecurityStubPrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackXxteaSecurityStubPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_XXTEA_SECURITY_STUB)


// Generated functions for use within plugin Serial
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SERIAL)
#define emberAfPluginSerialPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_SERIAL, __VA_ARGS__)
#define emberAfPluginSerialPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_SERIAL,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginSerialFlush()
#define emberAfPluginSerialDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_SERIAL) ) { x; }
#define emberAfPluginSerialPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_SERIAL, (buffer), (len), (withSpace))
#define emberAfPluginSerialPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_SERIAL, (buffer))
#else
#define emberAfPluginSerialPrint(...)
#define emberAfPluginSerialPrintln(...)
#define emberAfPluginSerialFlush()
#define emberAfPluginSerialDebugExec(x)
#define emberAfPluginSerialPrintBuffer(buffer, len, withSpace)
#define emberAfPluginSerialPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SERIAL)


// Generated functions for use within plugin PHY Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_PHY)
#define emberAfPluginPhyPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_PHY, __VA_ARGS__)
#define emberAfPluginPhyPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_PHY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginPhyFlush()
#define emberAfPluginPhyDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_PHY) ) { x; }
#define emberAfPluginPhyPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_PHY, (buffer), (len), (withSpace))
#define emberAfPluginPhyPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_PHY, (buffer))
#else
#define emberAfPluginPhyPrint(...)
#define emberAfPluginPhyPrintln(...)
#define emberAfPluginPhyFlush()
#define emberAfPluginPhyDebugExec(x)
#define emberAfPluginPhyPrintBuffer(buffer, len, withSpace)
#define emberAfPluginPhyPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_PHY)


// Generated functions for use within plugin RAIL Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY)
#define emberAfPluginRailLibraryPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY, __VA_ARGS__)
#define emberAfPluginRailLibraryPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginRailLibraryFlush()
#define emberAfPluginRailLibraryDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY) ) { x; }
#define emberAfPluginRailLibraryPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY, (buffer), (len), (withSpace))
#define emberAfPluginRailLibraryPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY, (buffer))
#else
#define emberAfPluginRailLibraryPrint(...)
#define emberAfPluginRailLibraryPrintln(...)
#define emberAfPluginRailLibraryFlush()
#define emberAfPluginRailLibraryDebugExec(x)
#define emberAfPluginRailLibraryPrintBuffer(buffer, len, withSpace)
#define emberAfPluginRailLibraryPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_RAIL_LIBRARY)


// Generated functions for use within plugin Command Interpreter
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER)
#define emberAfPluginCommandInterpreterPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER, __VA_ARGS__)
#define emberAfPluginCommandInterpreterPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginCommandInterpreterFlush()
#define emberAfPluginCommandInterpreterDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER) ) { x; }
#define emberAfPluginCommandInterpreterPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER, (buffer), (len), (withSpace))
#define emberAfPluginCommandInterpreterPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER, (buffer))
#else
#define emberAfPluginCommandInterpreterPrint(...)
#define emberAfPluginCommandInterpreterPrintln(...)
#define emberAfPluginCommandInterpreterFlush()
#define emberAfPluginCommandInterpreterDebugExec(x)
#define emberAfPluginCommandInterpreterPrintBuffer(buffer, len, withSpace)
#define emberAfPluginCommandInterpreterPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_COMMAND_INTERPRETER)


// Generated functions for use within plugin MAC Packet Queue
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE)
#define emberAfPluginStackMacQueuePrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE, __VA_ARGS__)
#define emberAfPluginStackMacQueuePrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackMacQueueFlush()
#define emberAfPluginStackMacQueueDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE) ) { x; }
#define emberAfPluginStackMacQueuePrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE, (buffer), (len), (withSpace))
#define emberAfPluginStackMacQueuePrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE, (buffer))
#else
#define emberAfPluginStackMacQueuePrint(...)
#define emberAfPluginStackMacQueuePrintln(...)
#define emberAfPluginStackMacQueueFlush()
#define emberAfPluginStackMacQueueDebugExec(x)
#define emberAfPluginStackMacQueuePrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackMacQueuePrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_MAC_QUEUE)


// Generated functions for use within plugin HAL Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HAL)
#define emberAfPluginHalPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_HAL, __VA_ARGS__)
#define emberAfPluginHalPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_HAL,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginHalFlush()
#define emberAfPluginHalDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_HAL) ) { x; }
#define emberAfPluginHalPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_HAL, (buffer), (len), (withSpace))
#define emberAfPluginHalPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_HAL, (buffer))
#else
#define emberAfPluginHalPrint(...)
#define emberAfPluginHalPrintln(...)
#define emberAfPluginHalFlush()
#define emberAfPluginHalDebugExec(x)
#define emberAfPluginHalPrintBuffer(buffer, len, withSpace)
#define emberAfPluginHalPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HAL)


// Generated functions for use within plugin Parent Support
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT)
#define emberAfPluginStackParentSupportPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT, __VA_ARGS__)
#define emberAfPluginStackParentSupportPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackParentSupportFlush()
#define emberAfPluginStackParentSupportDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT) ) { x; }
#define emberAfPluginStackParentSupportPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT, (buffer), (len), (withSpace))
#define emberAfPluginStackParentSupportPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT, (buffer))
#else
#define emberAfPluginStackParentSupportPrint(...)
#define emberAfPluginStackParentSupportPrintln(...)
#define emberAfPluginStackParentSupportFlush()
#define emberAfPluginStackParentSupportDebugExec(x)
#define emberAfPluginStackParentSupportPrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackParentSupportPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_PARENT_SUPPORT)


// Generated functions for use within plugin Security AES
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY)
#define emberAfPluginStackAesSecurityPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY, __VA_ARGS__)
#define emberAfPluginStackAesSecurityPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackAesSecurityFlush()
#define emberAfPluginStackAesSecurityDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY) ) { x; }
#define emberAfPluginStackAesSecurityPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY, (buffer), (len), (withSpace))
#define emberAfPluginStackAesSecurityPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY, (buffer))
#else
#define emberAfPluginStackAesSecurityPrint(...)
#define emberAfPluginStackAesSecurityPrintln(...)
#define emberAfPluginStackAesSecurityFlush()
#define emberAfPluginStackAesSecurityDebugExec(x)
#define emberAfPluginStackAesSecurityPrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackAesSecurityPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_AES_SECURITY)


// Generated functions for use within plugin Frequency Hopping stub
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB)
#define emberAfPluginFrequencyHoppingStubPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB, __VA_ARGS__)
#define emberAfPluginFrequencyHoppingStubPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginFrequencyHoppingStubFlush()
#define emberAfPluginFrequencyHoppingStubDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB) ) { x; }
#define emberAfPluginFrequencyHoppingStubPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB, (buffer), (len), (withSpace))
#define emberAfPluginFrequencyHoppingStubPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB, (buffer))
#else
#define emberAfPluginFrequencyHoppingStubPrint(...)
#define emberAfPluginFrequencyHoppingStubPrintln(...)
#define emberAfPluginFrequencyHoppingStubFlush()
#define emberAfPluginFrequencyHoppingStubDebugExec(x)
#define emberAfPluginFrequencyHoppingStubPrintBuffer(buffer, len, withSpace)
#define emberAfPluginFrequencyHoppingStubPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_FREQUENCY_HOPPING_STUB)


// Generated functions for use within plugin Stack Common
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_COMMON)
#define emberAfPluginStackCommonPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_COMMON, __VA_ARGS__)
#define emberAfPluginStackCommonPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_COMMON,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackCommonFlush()
#define emberAfPluginStackCommonDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_COMMON) ) { x; }
#define emberAfPluginStackCommonPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_COMMON, (buffer), (len), (withSpace))
#define emberAfPluginStackCommonPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_COMMON, (buffer))
#else
#define emberAfPluginStackCommonPrint(...)
#define emberAfPluginStackCommonPrintln(...)
#define emberAfPluginStackCommonFlush()
#define emberAfPluginStackCommonDebugExec(x)
#define emberAfPluginStackCommonPrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackCommonPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_COMMON)


// Generated functions for use within plugin Heartbeat
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HEARTBEAT)
#define emberAfPluginHeartbeatPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_HEARTBEAT, __VA_ARGS__)
#define emberAfPluginHeartbeatPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_HEARTBEAT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginHeartbeatFlush()
#define emberAfPluginHeartbeatDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_HEARTBEAT) ) { x; }
#define emberAfPluginHeartbeatPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_HEARTBEAT, (buffer), (len), (withSpace))
#define emberAfPluginHeartbeatPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_HEARTBEAT, (buffer))
#else
#define emberAfPluginHeartbeatPrint(...)
#define emberAfPluginHeartbeatPrintln(...)
#define emberAfPluginHeartbeatFlush()
#define emberAfPluginHeartbeatDebugExec(x)
#define emberAfPluginHeartbeatPrintBuffer(buffer, len, withSpace)
#define emberAfPluginHeartbeatPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_HEARTBEAT)


// Generated functions for use within plugin Debug Print
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT)
#define emberAfPluginDebugPrintPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT, __VA_ARGS__)
#define emberAfPluginDebugPrintPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginDebugPrintFlush()
#define emberAfPluginDebugPrintDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT) ) { x; }
#define emberAfPluginDebugPrintPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT, (buffer), (len), (withSpace))
#define emberAfPluginDebugPrintPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT, (buffer))
#else
#define emberAfPluginDebugPrintPrint(...)
#define emberAfPluginDebugPrintPrintln(...)
#define emberAfPluginDebugPrintFlush()
#define emberAfPluginDebugPrintDebugExec(x)
#define emberAfPluginDebugPrintPrintBuffer(buffer, len, withSpace)
#define emberAfPluginDebugPrintPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DEBUG_PRINT)


// Generated functions for use within plugin Form and Join
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN)
#define emberAfPluginStackFormAndJoinPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN, __VA_ARGS__)
#define emberAfPluginStackFormAndJoinPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackFormAndJoinFlush()
#define emberAfPluginStackFormAndJoinDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN) ) { x; }
#define emberAfPluginStackFormAndJoinPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN, (buffer), (len), (withSpace))
#define emberAfPluginStackFormAndJoinPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN, (buffer))
#else
#define emberAfPluginStackFormAndJoinPrint(...)
#define emberAfPluginStackFormAndJoinPrintln(...)
#define emberAfPluginStackFormAndJoinFlush()
#define emberAfPluginStackFormAndJoinDebugExec(x)
#define emberAfPluginStackFormAndJoinPrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackFormAndJoinPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_FORM_AND_JOIN)


// Generated functions for use within plugin Main
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MAIN)
#define emberAfPluginMainPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_MAIN, __VA_ARGS__)
#define emberAfPluginMainPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_MAIN,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginMainFlush()
#define emberAfPluginMainDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_MAIN) ) { x; }
#define emberAfPluginMainPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_MAIN, (buffer), (len), (withSpace))
#define emberAfPluginMainPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_MAIN, (buffer))
#else
#define emberAfPluginMainPrint(...)
#define emberAfPluginMainPrintln(...)
#define emberAfPluginMainFlush()
#define emberAfPluginMainDebugExec(x)
#define emberAfPluginMainPrintBuffer(buffer, len, withSpace)
#define emberAfPluginMainPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_MAIN)


// Generated functions for use within plugin Stack Packet Counters
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS)
#define emberAfPluginStackCountersPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS, __VA_ARGS__)
#define emberAfPluginStackCountersPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginStackCountersFlush()
#define emberAfPluginStackCountersDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS) ) { x; }
#define emberAfPluginStackCountersPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS, (buffer), (len), (withSpace))
#define emberAfPluginStackCountersPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS, (buffer))
#else
#define emberAfPluginStackCountersPrint(...)
#define emberAfPluginStackCountersPrintln(...)
#define emberAfPluginStackCountersFlush()
#define emberAfPluginStackCountersDebugExec(x)
#define emberAfPluginStackCountersPrintBuffer(buffer, len, withSpace)
#define emberAfPluginStackCountersPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_STACK_COUNTERS)


// Generated functions for use within plugin Simulated EEPROM version 1 Library
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1)
#define emberAfPluginSimEeprom1Print(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1, __VA_ARGS__)
#define emberAfPluginSimEeprom1Println(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginSimEeprom1Flush()
#define emberAfPluginSimEeprom1DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1) ) { x; }
#define emberAfPluginSimEeprom1PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1, (buffer), (len), (withSpace))
#define emberAfPluginSimEeprom1PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1, (buffer))
#else
#define emberAfPluginSimEeprom1Print(...)
#define emberAfPluginSimEeprom1Println(...)
#define emberAfPluginSimEeprom1Flush()
#define emberAfPluginSimEeprom1DebugExec(x)
#define emberAfPluginSimEeprom1PrintBuffer(buffer, len, withSpace)
#define emberAfPluginSimEeprom1PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_SIM_EEPROM1)


// Generated functions for use within plugin Diagnostic
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC)
#define emberAfPluginDiagnosticPrint(...) emberAfPrint(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC, __VA_ARGS__)
#define emberAfPluginDiagnosticPrintln(...) emberAfPrintln(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfPluginDiagnosticFlush()
#define emberAfPluginDiagnosticDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC) ) { x; }
#define emberAfPluginDiagnosticPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC, (buffer), (len), (withSpace))
#define emberAfPluginDiagnosticPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC, (buffer))
#else
#define emberAfPluginDiagnosticPrint(...)
#define emberAfPluginDiagnosticPrintln(...)
#define emberAfPluginDiagnosticFlush()
#define emberAfPluginDiagnosticDebugExec(x)
#define emberAfPluginDiagnosticPrintBuffer(buffer, len, withSpace)
#define emberAfPluginDiagnosticPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_PLUGIN_DIAGNOSTIC)


// Generated functions for use within area Core
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CORE)
#define emberAfCorePrint(...) emberAfPrint(EMBER_AF_PRINT_CORE, __VA_ARGS__)
#define emberAfCorePrintln(...) emberAfPrintln(EMBER_AF_PRINT_CORE,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCoreFlush()
#define emberAfCoreDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CORE) ) { x; }
#define emberAfCorePrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CORE, (buffer), (len), (withSpace))
#define emberAfCorePrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CORE, (buffer))
#else
#define emberAfCorePrint(...)
#define emberAfCorePrintln(...)
#define emberAfCoreFlush()
#define emberAfCoreDebugExec(x)
#define emberAfCorePrintBuffer(buffer, len, withSpace)
#define emberAfCorePrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CORE)


// Generated functions for use within area Debug
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_DEBUG)
#define emberAfDebugPrint(...) emberAfPrint(EMBER_AF_PRINT_DEBUG, __VA_ARGS__)
#define emberAfDebugPrintln(...) emberAfPrintln(EMBER_AF_PRINT_DEBUG,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfDebugFlush()
#define emberAfDebugDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_DEBUG) ) { x; }
#define emberAfDebugPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_DEBUG, (buffer), (len), (withSpace))
#define emberAfDebugPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_DEBUG, (buffer))
#else
#define emberAfDebugPrint(...)
#define emberAfDebugPrintln(...)
#define emberAfDebugFlush()
#define emberAfDebugDebugExec(x)
#define emberAfDebugPrintBuffer(buffer, len, withSpace)
#define emberAfDebugPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_DEBUG)


// Generated functions for use within area Application
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_APP)
#define emberAfAppPrint(...) emberAfPrint(EMBER_AF_PRINT_APP, __VA_ARGS__)
#define emberAfAppPrintln(...) emberAfPrintln(EMBER_AF_PRINT_APP,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfAppFlush()
#define emberAfAppDebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_APP) ) { x; }
#define emberAfAppPrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_APP, (buffer), (len), (withSpace))
#define emberAfAppPrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_APP, (buffer))
#else
#define emberAfAppPrint(...)
#define emberAfAppPrintln(...)
#define emberAfAppFlush()
#define emberAfAppDebugExec(x)
#define emberAfAppPrintBuffer(buffer, len, withSpace)
#define emberAfAppPrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_APP)


// Generated functions for use within area Custom messages (1)
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM1)
#define emberAfCustom1Print(...) emberAfPrint(EMBER_AF_PRINT_CUSTOM1, __VA_ARGS__)
#define emberAfCustom1Println(...) emberAfPrintln(EMBER_AF_PRINT_CUSTOM1,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCustom1Flush()
#define emberAfCustom1DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CUSTOM1) ) { x; }
#define emberAfCustom1PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CUSTOM1, (buffer), (len), (withSpace))
#define emberAfCustom1PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CUSTOM1, (buffer))
#else
#define emberAfCustom1Print(...)
#define emberAfCustom1Println(...)
#define emberAfCustom1Flush()
#define emberAfCustom1DebugExec(x)
#define emberAfCustom1PrintBuffer(buffer, len, withSpace)
#define emberAfCustom1PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM1)


// Generated functions for use within area Custom messages (2)
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM2)
#define emberAfCustom2Print(...) emberAfPrint(EMBER_AF_PRINT_CUSTOM2, __VA_ARGS__)
#define emberAfCustom2Println(...) emberAfPrintln(EMBER_AF_PRINT_CUSTOM2,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCustom2Flush()
#define emberAfCustom2DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CUSTOM2) ) { x; }
#define emberAfCustom2PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CUSTOM2, (buffer), (len), (withSpace))
#define emberAfCustom2PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CUSTOM2, (buffer))
#else
#define emberAfCustom2Print(...)
#define emberAfCustom2Println(...)
#define emberAfCustom2Flush()
#define emberAfCustom2DebugExec(x)
#define emberAfCustom2PrintBuffer(buffer, len, withSpace)
#define emberAfCustom2PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM2)


// Generated functions for use within area Custom messages (3)
#if defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM3)
#define emberAfCustom3Print(...) emberAfPrint(EMBER_AF_PRINT_CUSTOM3, __VA_ARGS__)
#define emberAfCustom3Println(...) emberAfPrintln(EMBER_AF_PRINT_CUSTOM3,  __VA_ARGS__)
// Blocking IO is enabled for all serial ports, therefore flush calls are unnecessary.
#define emberAfCustom3Flush()
#define emberAfCustom3DebugExec(x) if ( emberAfPrintEnabled(EMBER_AF_PRINT_CUSTOM3) ) { x; }
#define emberAfCustom3PrintBuffer(buffer, len, withSpace) emberAfPrintBuffer(EMBER_AF_PRINT_CUSTOM3, (buffer), (len), (withSpace))
#define emberAfCustom3PrintString(buffer) emberAfPrintString(EMBER_AF_PRINT_CUSTOM3, (buffer))
#else
#define emberAfCustom3Print(...)
#define emberAfCustom3Println(...)
#define emberAfCustom3Flush()
#define emberAfCustom3DebugExec(x)
#define emberAfCustom3PrintBuffer(buffer, len, withSpace)
#define emberAfCustom3PrintString(buffer)
#endif //defined(EMBER_AF_PRINT_ENABLE) && defined(EMBER_AF_PRINT_CUSTOM3)


#endif // __EMBER_AF_DEBUG_PRINTING_CONFIGURATION__
