// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"

// Init function declarations.
void emberAfPluginHeartbeatInit(void);
void emberCommandReaderInit(void);

void emberAfInit(void)
{
  emberAfPluginHeartbeatInit();
  emberCommandReaderInit();
}

// Tick function declarations.
void emberAfPluginCommandInterpreterTickCallback(void);

void emberAfTick(void)
{
  emberAfPluginCommandInterpreterTickCallback();
}

void emberAfStackStatus(EmberStatus status)
{
}

void emberAfStackIsr(void)
{
}

void emberAfIncomingMessage(EmberIncomingMessage* message)
{
}

void emberAfIncomingMacMessage(EmberIncomingMacMessage* message)
{
}

void emberAfMessageSent(EmberStatus status, EmberOutgoingMessage* message)
{
}

void emberAfMacMessageSent(EmberStatus status, EmberOutgoingMacMessage* message)
{
}

void emberAfChildJoin(EmberNodeType nodeType, EmberNodeId nodeId)
{
}

void emberAfIncomingBeacon(EmberPanId panId, EmberNodeId nodeId, int8_t rssi, bool permitJoining, uint8_t payloadLength, uint8_t* payload)
{
}

void emberAfIncomingBeaconExtended(EmberPanId panId, EmberMacAddress *source, int8_t rssi, bool permitJoining, uint8_t beaconFieldsLength, uint8_t *beaconFields, uint8_t beaconPayloadLength, uint8_t *beaconPayload)
{
}

void emberAfActiveScanComplete(void)
{
}

void emberAfEnergyScanComplete(int8_t mean, int8_t min, int8_t max, uint16_t variance)
{
}

// MarkApplicationBuffers function declarations.
void emberAfMarkApplicationBuffersCallback(void);

void emberMarkApplicationBuffersHandler(void)
{
  emberAfMarkApplicationBuffersCallback();
}

void emberAfFrequencyHoppingStartClientComplete(EmberStatus status)
{
}

void emberAfRadioNeedsCalibrating(void)
{
}
